FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
EXPOSE 5064

ENV ASPNETCORE_URLS=http://+:5064

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Debug -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "ChecklistAPI.dll"]


### one generated by vscode
# FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
# WORKDIR /app
# EXPOSE 5064

# ENV ASPNETCORE_URLS=http://+:5064

# USER app
# FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0 AS build
# ARG configuration=Release
# WORKDIR /src
# COPY ["ChecklistAPI/ChecklistAPI.csproj", "ChecklistAPI/"]
# RUN dotnet restore "ChecklistAPI/ChecklistAPI.csproj"
# COPY . .
# WORKDIR "/src/ChecklistAPI"
# RUN dotnet build "ChecklistAPI.csproj" -c $configuration -o /app/build

# FROM build AS publish
# ARG configuration=Release
# RUN dotnet publish "ChecklistAPI.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

# FROM base AS final
# WORKDIR /app
# COPY --from=publish /app/publish .
# ENTRYPOINT ["dotnet", "ChecklistAPI.dll"]
